fhome_work3
Alex-Merfi/Alex-Merfi pull request #2
Opened 2021-12-09 09:20 UTC by Alex-Merfi

next home work. I used pop(),while, for and in

2021-12-09 09:51 UTC, Alex-Merfi commented
counting numbers

2021-12-10 06:28 UTC, vadym-khodak requested changes
Молодець що розібрався як робити Pull Requests.
Але тут я не бачу виконання домашнього завдання, воно було зовсім іншим.
[Переглянь будь ласка умови домашніх завдань на цьому слайді](https://docs.google.com/presentation/d/1zlogDvksmR40f8fwlJTENeQQiUmRU1_qjuXd0M3u4OA/edit#slide=id.gc6f919934_0_57)

2021-12-10 06:28 UTC, vadym-khodak commented on .idea/htask/numbs.py
> +x=4+7
Завдання про числа було "написати програму яка буде питати користувача ввести два числа та друкуватиме у терміналі суму та різницю цих чисел".
Ти не міг би переробити це?

2021-12-10 06:28 UTC, vadym-khodak commented on .idea/htask/htask3.py
> +    print(confirmed_user.title())
Навіщо ти викликаєш `title()` двічі?

2021-12-10 06:28 UTC, vadym-khodak commented on .idea/htask/htask3.py
> +    print(confirmed_user.title())
Що цей код має робити?
Завдання про роботу зі списками було зовсім іншим.

2022-04-06 08:23 UTC, merged